export type PartnerCompany = {
  name: string
  domain: string
}

export const partnerCompanies: PartnerCompany[] = [
  { name: 'Amazon', domain: 'amazon.com' },
  { name: 'Microsoft', domain: 'microsoft.com' },
  { name: 'Google', domain: 'google.com' },
  { name: 'Apple', domain: 'apple.com' },
  { name: 'Meta', domain: 'meta.com' },
  { name: 'NVIDIA', domain: 'nvidia.com' },
  { name: 'Oracle', domain: 'oracle.com' },
  { name: 'Salesforce', domain: 'salesforce.com' },
  { name: 'IBM', domain: 'ibm.com' },
  { name: 'Intel', domain: 'intel.com' },
  { name: 'Cisco', domain: 'cisco.com' },
  { name: 'Adobe', domain: 'adobe.com' },
  { name: 'ServiceNow', domain: 'servicenow.com' },
  { name: 'PayPal', domain: 'paypal.com' },
  { name: 'Qualcomm', domain: 'qualcomm.com' },
  { name: 'Dell Technologies', domain: 'dell.com' },
  { name: 'Uber', domain: 'uber.com' },
  { name: 'Tesla', domain: 'tesla.com' },
  { name: 'Walmart', domain: 'walmart.com' },
  { name: 'Goldman Sachs', domain: 'goldmansachs.com' },
  { name: 'Pfizer', domain: 'pfizer.com' },
  { name: 'General Electric', domain: 'ge.com' },
  { name: 'Boeing', domain: 'boeing.com' },
  { name: 'Ford', domain: 'ford.com' },
  { name: 'PepsiCo', domain: 'pepsico.com' },
  { name: 'Coca-Cola', domain: 'coca-cola.com' },
  { name: "Procter & Gamble", domain: 'pg.com' },
  { name: 'Visa', domain: 'visa.com' },
  { name: 'Mastercard', domain: 'mastercard.com' },
  { name: 'AT&T', domain: 'att.com' },
  { name: 'Verizon', domain: 'verizon.com' },
  { name: 'Accenture', domain: 'accenture.com' },
  { name: 'Deloitte', domain: 'deloitte.com' },
  { name: 'Cognizant', domain: 'cognizant.com' },
  { name: 'Capgemini', domain: 'capgemini.com' },
  { name: 'Infosys', domain: 'infosys.com' },
  { name: 'Wipro', domain: 'wipro.com' },
  { name: 'HCLTech', domain: 'hcltech.com' },
  { name: 'Tech Mahindra', domain: 'techmahindra.com' },
  { name: 'TCS', domain: 'tcs.com' },
  { name: 'LTIMindtree', domain: 'ltimindtree.com' },
  { name: 'DXC Technology', domain: 'dxc.com' },
  { name: 'EPAM Systems', domain: 'epam.com' },
  { name: 'Globant', domain: 'globant.com' },
]
